#!/bin/bash
gcc -o main main.c -lm

while true
do
	clear
	cat zastavka.txt
	printf "\n             MENU\n"
	printf "1)Контрольный расчет в среде Wxmaxima\n"
	printf "2)Расчет параметра на языке Си\n"
	printf "3)Построение графиков Wxmaxima\n"
	printf "[Type \"exit\" to quit]\n Выбор:"

	read choice
	case $choice in

		1)
		wxmaxima raschet.wxmx
		;;
		2)
		./main	
		;;
		3) 
		wxmaxima graph.wxmx
		;;
		exit)
		exit
		;;

	esac
	clear
done
